### ISSUE TITLE
Isotopes and Atomic Mass Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/isotopes-and-atomic-mass#19]
## Design
- [x] **Design doc created** (Date: 08/16/2015) 
 - [x] Make phethelp@gmail.com owner, share with phet-team
 - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 10/01/2015)
- [x] **Design concept complete**  (Date: 10/13/2015)
- [x] **Wireframes complete** (Date: 10/30/2015) 
- [x] **Mockups complete** (Date: 12/11/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 02/24/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 02/26/2016) 
  - [x] Performance acceptable
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Check compatible activities  
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Activities and gooru spreadsheet
  - [x] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date:10/16/2014) 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Existing sim tested for bugs, issues reported in repo
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [x] **Initial development started** (Date: 11/01/2014)
- [x] **Sim feature complete** (Date: 02/25/2016) 
- [x] **Code review complete** (Date:05/11/2016) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 05/20/2016)
  - [x] Update repo README to published template

## QA
- [x] **Dev testing complete** (Date: 01/28/2016) 
- [x] **First release candidate** (Date: 05/16/2016)
 - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
 - [x] Test matrix deemed complete

**Comment by ariel-phet** [comment]
@amyh-phet assigning to you for the colorblind check and pasting notes into the design doc.

**Comment by amyh-phet** [comment]
@ariel-phet   Notes are now in design doc.  Sending this back to you for next steps on the checklist.

**Comment by ariel-phet** [comment]
@aadish can you verify the port strings and "model description" steps in the checklist above and then reassign to me?

**Comment by aadish** [comment]
@ariel-phet  done

**Comment by ariel-phet** [comment]
@amyh-phet looks like just one particular item left :). Assigning to you

**Comment by amyh-phet** [comment]
Sim primer complete.  Closing as checklist is completed
